// Audit rows describe individual country trajectories within sector/partner slices.
const auditSection=document.createElement('section');
auditSection.id='audits';auditSection.className='hidden';
auditSection.innerHTML=`<h2>Trajectory audit</h2>
<p>Core indicators, bilateral flows, and other outputs. Each row fixes a sector or partner and selects the country with the largest cumulative absolute difference over aligned years.</p>
<p><small>sMAPE ranges from 0% to 200%. Both-zero years contribute zero; large percentages near zero can reflect small absolute changes. SSE and cumulative differences retain each variable’s units. Undefined correlation is shown as —.</small></p>
<div class="row" id="laneOverview"></div>
<div class="row"><label>Category<select id="auditLane"><option value="Core">Core</option><option value="Dyadic">Dyadic</option><option value="Other">Other / monadic / global</option></select></label><label>Find a variable, sector, or country<input id="auditSearch" placeholder="e.g. GDP, Solar, China"></label></div>
<p><a id="auditExport">Download category audit ledger</a> <span id="auditCount"></span></p>
<div class="scroll"><table><thead><tr><th>Tracked output</th><th>Selected cohort</th><th>sMAPE %</th><th>SSE</th><th>Pearson r</th><th>Crossings</th><th>First flagged year</th><th>Peak difference year</th></tr></thead><tbody id="auditRows"></tbody></table></div>`;
$('results').after(auditSection);
let auditReport;
const originalShow=show;
show=function(report){originalShow(report);text($('totals'),'Baseline: '+report.run1.split(/[/\\]/).pop()+' · Comparison: '+report.run2.split(/[/\\]/).pop()+' · '+$('totals').textContent);auditReport=report;$('audits').classList.remove('hidden');overview();renderAudit();};
const comparisonButton=$('compare').onclick;
$('compare').onclick=async()=>{await comparisonButton();if($('compare').disabled)$('audits').classList.add('hidden');};
$('auditLane').onchange=renderAudit;$('auditSearch').oninput=renderAudit;
let coreVariables=new Set();
const coreButton=document.createElement('button');coreButton.className='secondary';text(coreButton,'Select core indicators');$('all').after(document.createTextNode(' '),coreButton);coreButton.onclick=()=>Array.from($('variables').options).forEach(o=>o.selected=coreVariables.has(o.value));
function ranked(lane){return (auditReport.audits||[]).filter(row=>row.lane===lane).sort((a,b)=>(b.mean_smape??-1)-(a.mean_smape??-1)||a.tracked_variable.localeCompare(b.tracked_variable));}
function renderAudit(){if(!auditReport)return;const lane=$('auditLane').value,query=$('auditSearch').value.toLowerCase();const rows=ranked(lane).filter(row=>(row.tracked_variable+' '+row.worst_cohort).toLowerCase().includes(query));$('auditRows').replaceChildren();text($('auditCount'),rows.length+' trajectory slices');$('auditExport').href='/api/export?job='+job+'&lane='+lane;for(const row of rows){const tr=document.createElement('tr');tr.dataset.variable=row.base_variable;for(const value of [row.tracked_variable,row.worst_cohort,number(row.mean_smape),number(row.sse),number(row.pearson_r),row.sign_flips,row.first_divergence_year??'—',row.max_divergence_year??'—']){const td=document.createElement('td');text(td,value);tr.append(td)}tr.onclick=handle(async()=>{active=row.base_variable;await series(row.selectors);$('detail').scrollIntoView({behavior:'smooth',block:'start'})});$('auditRows').append(tr)}}
function overview(){const container=$('laneOverview');container.replaceChildren();for(const lane of ['Core','Dyadic','Other']){const card=document.createElement('div');card.style.cssText='flex:1;min-width:260px';const heading=document.createElement('h3');text(heading,lane+' · highest sMAPE');card.append(heading);const rows=ranked(lane).filter(r=>r.mean_smape!==null).slice(0,10);if(!rows.length){const p=document.createElement('p');text(p,'No compared outputs in this category.');card.append(p)}const maximum=Math.max(1,...rows.map(r=>r.mean_smape));for(const row of rows){const button=document.createElement('button');button.className='secondary';button.style.cssText='display:block;width:100%;text-align:left;margin:6px 0;padding:7px;font-size:12px;background:linear-gradient(90deg,#dcefee '+(row.mean_smape/maximum*100)+'%,white 0)';text(button,row.tracked_variable+' · '+row.mean_smape.toFixed(2)+'%');button.title=row.worst_cohort;button.onclick=handle(async()=>{active=row.base_variable;await series(row.selectors);$('detail').scrollIntoView({behavior:'smooth'})});card.append(button)}container.append(card)}}
const metricText=document.createElement('p');metricText.id='trajectoryMetrics';$('pointNote').before(metricText);
const deltaHeading=document.createElement('h3');text(deltaHeading,'Difference over time · comparison − baseline');
const deltaChart=document.createElementNS('http://www.w3.org/2000/svg','svg');deltaChart.id='deltaChart';deltaChart.setAttribute('viewBox','0 0 1000 320');deltaChart.setAttribute('role','img');deltaChart.setAttribute('aria-label','Difference trajectory');$('pointNote').after(deltaHeading,deltaChart);
const saveButton=document.createElement('button');saveButton.className='secondary';text(saveButton,'Save trajectory charts as SVG');deltaChart.after(saveButton);
saveButton.onclick=()=>{const combined=document.createElementNS('http://www.w3.org/2000/svg','svg');combined.setAttribute('xmlns','http://www.w3.org/2000/svg');combined.setAttribute('viewBox','0 0 1000 700');combined.setAttribute('width','1000');combined.setAttribute('height','700');for(const [id,offset] of [['chart',30],['deltaChart',370]]){const group=document.createElementNS(combined.namespaceURI,'g');group.setAttribute('transform','translate(0 '+offset+')');for(const child of $(id).children)group.append(child.cloneNode(true));combined.append(group)}const title=document.createElementNS(combined.namespaceURI,'text');title.setAttribute('x','70');title.setAttribute('y','20');title.textContent=$('chartTitle').textContent;combined.prepend(title);const blob=new Blob([new XMLSerializer().serializeToString(combined)],{type:'image/svg+xml'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=active+'_trajectories.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
// Keep selector and chart behavior in one place; enrich the response with metrics.
const originalApi=api;
api=async function(path,body){const response=await originalApi(path,body);if(response.core_variables)coreVariables=new Set(response.core_variables);return response;};
function enhanceSeries(response){const m=response.metrics;const labels=response.options.map((opts,i)=>opts.find(o=>o.key===response.chosen[i])?.label||response.chosen[i]);text($('chartTitle'),active+' · '+(labels.join(' / ')||'Global series'));text(metricText,'sMAPE '+number(m.mean_smape)+'% · SSE '+number(m.sse)+' · Pearson r '+number(m.pearson_r)+' · Crossings '+m.sign_flips+' · First flagged year '+(m.first_divergence_year??'—')+' · Peak difference year '+(m.max_divergence_year??'—')+' · Nonfinite years '+m.nonfinite_years);drawDelta(response.points);}

function drawDelta(points){const svg=$('deltaChart');svg.replaceChildren();const ns=svg.namespaceURI;function add(tag,attrs,content){const element=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))element.setAttribute(k,v);if(content!=null)element.textContent=content;svg.append(element)}const values=points.filter(p=>p[1]!==null&&p[2]!==null).map(p=>p[2]-p[1]);if(!values.length)return;let low=Math.min(0,...values),high=Math.max(0,...values);if(low===high){low-=1;high+=1}const x=t=>70+(t-points[0][0])/Math.max(1,points.at(-1)[0]-points[0][0])*900,y=v=>270-(v-low)/(high-low)*240;for(let i=0;i<5;i++){const v=low+(high-low)*i/4;add('line',{x1:70,x2:970,y1:y(v),y2:y(v),stroke:'#e2e9ec'});add('text',{x:64,y:y(v)+4,'text-anchor':'end','font-size':12},number(v))}add('line',{x1:70,x2:970,y1:y(0),y2:y(0),stroke:'#97adb5','stroke-dasharray':'4 4'});let path='',open=false,lastYear;for(const p of points){if(p[1]===null||p[2]===null){open=false;continue}if(lastYear!==undefined&&p[0]!==lastYear+1)open=false;path+=(open?'L':'M')+x(p[0])+','+y(p[2]-p[1]);open=true;lastYear=p[0]}add('path',{d:path,fill:'none',stroke:'#8054aa','stroke-width':2});for(const year of [points[0][0],points.at(-1)[0]])add('text',{x:x(year),y:300,'text-anchor':'middle','font-size':12},year);}